name: Ruby Gem

on:
  release:
    types: [published]

permissions:
  id-token: write # allows the JWT to be requested from GitHub's OIDC provider
  contents: read # This is required for actions/checkout

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.7

      # for now, skip github packages and just publish to ruby gems
      # - name: Publish to GPR
      #   run: |
      #     mkdir -p $HOME/.gem
      #     touch $HOME/.gem/credentials
      #     chmod 0600 $HOME/.gem/credentials
      #     printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
      #     gem build *.gemspec
      #     gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      #   env:
      #     GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
      #     OWNER: ${{ github.repository_owner }}

      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

      - name: Send message to Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          PROJECT_NAME: "Events SDK Ruby - RubyGems.org Package"
          PACKAGE_URL: "https://rubygems.org/gems/events-sdk-ruby/"
        with:
          channel-id: ${{ secrets.SLACK_RELEASE_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New release: ${{ env.PROJECT_NAME }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Release: <${{ env.PACKAGE_URL }}>*\n"
                  }
                }
              ]
            }
